"""add conversation id to entries

Revision ID: 5a10049601be
Revises: 5e81cead6656
Create Date: 2025-10-04 15:34:45.025505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a10049601be'
down_revision: Union[str, Sequence[str], None] = '5e81cead6656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('conversation_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'conversation_id')
    # ### end Alembic commands ###
