"""add type column to entries

Revision ID: 5e81cead6656
Revises: cf22f6ed42aa
Create Date: 2025-10-04 11:58:40.475603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e81cead6656'
down_revision: Union[str, Sequence[str], None] = 'cf22f6ed42aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'type')
    # ### end Alembic commands ###
