"""add imgur field

Revision ID: 714a21a338c0
Revises: a7e4396e5696
Create Date: 2025-10-04 16:20:27.671352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '714a21a338c0'
down_revision: Union[str, Sequence[str], None] = 'a7e4396e5696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('imgur_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'imgur_url')
    # ### end Alembic commands ###
