"""add new column to entries

Revision ID: cf22f6ed42aa
Revises: 7df132a7ff45
Create Date: 2025-10-04 11:16:49.566396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf22f6ed42aa'
down_revision: Union[str, Sequence[str], None] = '7df132a7ff45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('sentiment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'sentiment')
    # ### end Alembic commands ###
